### ISSUE TITLE
mvn clean install /aixm-5.1 Unknown lifecycle phase error

### ISSUE THREAD

**Issue by IamMashed** [faa-swim/fns-client#2]
I try to install submodule dependencies but i get the following error:
`(venv)fns-client git:(v1.0) mvn clean install /aixm-5.1

[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< us.dot.faa.swim.fns:fns-client >-------------------
[INFO] Building fns-client 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.190 s
[INFO] Finished at: 2021-03-11T21:21:49+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "/aixm-5.1". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
`

I am on macos big sur 11.1 (20C69)

`(venv) ‚ûú  fns-client git:(v1.0) mvn --version`
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.1", arch: "x86_64", family: "mac"

`(venv) ‚ûú  fns-client git:(v1.0) java --version`
java 14.0.2 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

**Comment by yongwang** [comment]
you have to cd into that folder and then run `mvn clean install`

```
cd aixm-5.1/
mvn clean install
```

**Comment by armFAActr** [comment]
Updated readme to include -f with pom.xml

mvn clean install -f ./aixm-5.1/pom.xml
mvn clean install -f ./jms-client/pom.xml
mvn clean install -f ./swim-utilities/pom.xml
