### ISSUE TITLE
Error while parsing xml file from SFTP server

### ISSUE THREAD

**Issue by rhishirajnema** [faa-swim/fns-client#4]
Looks like there is some issue while parsing xml file during Notam db initialization. 

`java.io.IOException error 
    ChannelSftp.java:1448 com.jcraft.jsch.ChannelSftp$2.read
    InflaterInputStream.java:243 java.util.zip.InflaterInputStream.fill
    InflaterInputStream.java:159 java.util.zip.InflaterInputStream.read
    GZIPInputStream.java:118 java.util.zip.GZIPInputStream.read
    XMLEntityManager.java:3064 com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read
    UTF8Reader.java:303 com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read
    XMLEntityScanner.java:1904 com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load
    XMLEntityScanner.java:1560 com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar
    XMLDocumentFragmentScannerImpl.java:2746 com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next
    XMLDocumentScannerImpl.java:605 com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next
    XMLNSDocumentScannerImpl.java:112 com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next
    XMLDocumentFragmentScannerImpl.java:534 com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument
    XML11Configuration.java:888 com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse
    XML11Configuration.java:824 com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse
    XMLParser.java:141 com.sun.org.apache.xerces.internal.parsers.XMLParser.parse
    AbstractSAXParser.java:1216 com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse
    SAXParserImpl.java:635 com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse
    FilParser.java:53 com.soschat.notam.source.fil.FilParser.parseFilFile
FnsClient.java:259 com.soschat.notam.source.fns.FnsClient.loadNotams
    FnsClient.java:188 com.soschat.notam.source.fns.FnsClient.initalizeNotamDbFromFil
    FnsClient.java:105 com.soschat.notam.source.fns.FnsClient$2.onMissed
    MissedMessageTracker.java:161 us.dot.faa.swim.utilities.MissedMessageTracker.run
`

**Comment by armFAActr** [comment]
The FilClient provides an inputstream to the FIL file parser. If the config contains a filFIleSavePath then the FIL file is downloaded and a FileInputStream is provided. If no filFileSavePath is set then the inputstream returned is the sftp stream for the file. The later prevents the need to store the fil file before processing but does lead to the potential of an IO error if the sftp stream is interrupted before processing of the file is complete which is likely the cause here.

	if (this.config.filFileSavePath != null && !this.config.filFileSavePath.isEmpty()) {
		filFileLocalPath = this.config.filFileSavePath.concat(this.config.filFileName);
		sftpChannel.get(this.config.filFileName, filFileLocalPath);
		return new GZIPInputStream(new FileInputStream(filFileLocalPath));
	} else {
		return new GZIPInputStream(sftpChannel.get(this.config.filFileName));
	}

**Comment by rhishirajnema** [comment]
Thank you, I will try that.

**Comment by rhishirajnema** [comment]
This looks like to be resolved. Thanks!
